train:
  _target_: dataset.dataset_2_random_xl.SlakhDataset # choosing which data class to use
  root_dir: "/data2/kinwai/slakh2100_flac_redux/train"
  mel_length: ${mel_length}
  event_length: ${event_length}
  midi_folder: MIDI
  inst_filename: inst_names.json
  audio_filename: mix_16k.wav
val:
  _target_: dataset.dataset_2_random_xl.SlakhDataset # choosing which data class to use
  root_dir: "/data2/kinwai/slakh2100_flac_redux/validation/"
  mel_length: ${mel_length}
  event_length: ${event_length}
  midi_folder: MIDI
  inst_filename: inst_names.json
  audio_filename: mix_16k.wav    
test:
  root_dir: "/data/slakh2100_flac_redux/validation"
collate_fn: dataset.dataset_2_random_xl.collate_fn
