train:
  _target_: dataset.dataset_2_random.SlakhDataset # choosing which data class to use
  root_dir: "/data2/kinwai/slakh2100_flac_redux/train"
  mel_length: ${mel_length}
  event_length: ${event_length}
  midi_folder: MIDI
  inst_filename: inst_names.json
  audio_filename: mix_16k.wav
  num_rows_per_batch: ${num_rows_per_batch}
  split_frame_length: ${split_frame_length}
  is_deterministic: ${dataset_is_deterministic}
  is_randomize_tokens: ${dataset_is_randomize_tokens}
  use_tf_spectral_ops: ${dataset_use_tf_spectral_ops}
val:
  _target_: dataset.dataset_2_random.SlakhDataset # choosing which data class to use
  root_dir: "/data2/kinwai/slakh2100_flac_redux/validation/"
  mel_length: ${mel_length}
  event_length: ${event_length}
  midi_folder: MIDI
  inst_filename: inst_names.json
  audio_filename: mix_16k.wav   
  num_rows_per_batch: ${num_rows_per_batch}
  split_frame_length: ${split_frame_length}
  is_deterministic: ${dataset_is_deterministic}
  is_randomize_tokens: ${dataset_is_randomize_tokens}
  use_tf_spectral_ops: ${dataset_use_tf_spectral_ops}
test:
  root_dir: "/data/slakh2100_flac_redux/test"
collate_fn: dataset.dataset_2_random.collate_fn
